### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by dragondgold** [vishnubob/octocmd#5]
I'm trying to install octocmd on Ubuntu 12.10 using: `pip install https://github.com/vishnubob/octocmd/archive/master.zip` but I get an error, here is the log:

```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    install_requires = [str(ir.req) for ir in install_requires]
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_file.py", line 72, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'
```

**Comment by vishnubob** [comment]
I just merged #4, which fixes this issue.
