### ISSUE TITLE
octocmd print throws exception

### ISSUE THREAD

**Issue by alejandroLoz** [vishnubob/octocmd#9]
Hi,  

When I try to print a gcode on a fresh octoPI (http://mirror.tsone.net.uk/octopi/) image
I get the following exception 

octocmd print key.gcodeCould
Could not find openscad
Could not find cura
[Sun Nov 29 23:44:09 2015 octocmd] uploading, selecting, printing key.gcode on O                                                                                                             ctoPrint
Traceback (most recent call last):
  File "/usr/local/bin/octocmd", line 504, in <module>
    process(args)
  File "/usr/local/bin/octocmd", line 497, in process
    process_target(args)
  File "/usr/local/bin/octocmd", line 489, in process_target
    pipe.transform(infn, targetfn)
  File "/usr/local/bin/octocmd", line 109, in transform
    self.run_pipeline(pipeline, *_kw)
  File "/usr/local/bin/octocmd", line 99, in run_pipeline
    method(inputfn, outputfn, *_kw)
  File "/usr/local/bin/octocmd", line 341, in transform_gcode_to_print
    self.transform(inputfn, outputfn, *_kw)
  File "/usr/local/bin/octocmd", line 134, in transform
    self._transform(inputfn, outputfn, *_args)
  File "/usr/local/bin/octocmd", line 328, in _transform
    self.post_file(inputfn, filename=filename, upload=True)
  File "/usr/local/bin/octocmd", line 296, in post_file
    res = self.post(url, *_params)
  File "/usr/local/bin/octocmd", line 245, in post
    return self.session.post(self.url + url, *_kw)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 511,                                                                                                              in post
    return self.request('POST', url, data=data, json=json, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468,                                                                                                              in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576,                                                                                                              in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 412,                                                                                                              in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",                                                                                                             ))

Please take into account that I can print from octoprint's from the GUI without any issues and the "status" command throws the regular stuff that it should (State: Operational .....)

What could be wrong?

**Comment by johannesrauch** [comment]
I've got the same problem. 

Everytime i execute the 'octocmd print example.gcode' command, i get a similar error message like you, although the printer starts doing his work.

I'm afraid the threads dead though, but any help would be apreciated.
